### ISSUE TITLE
Some examples and some errors

### ISSUE THREAD

**Issue by christophsax** [srlanalytics/BDFM#13]
Some minimal examples that I ran before. I get errors when:

- [x] forecasting single series (not sure if this meaningful or possible, but at least we should fail gracefully)
- [x] Forecasting, just a small conversion to timeseries issue.
- [x] Why are the levels of the predicted values, e.g., for `mdeaths`, so different from the original values?

``` r
library(BDFM)
packageVersion("BDFM")
#> [1] '0.0.1'
library(tsbox)

fdeaths0 <- fdeaths
fdeaths0[length(fdeaths0)] <- NA
dta <- ts_c(fdeaths0, mdeaths)

# forecasting single series
dfm(fdeaths, forecast = 2)
#> Error in DSmooth(B, q, H, R, Y[, -(1:m)]): Not a matrix.

# multiple series (this works)
ts_plot(ts_c(dta, predict(dfm(dta))))
```

![](https://i.imgur.com/xWRuQqI.png)

``` r

# but this doesn't
dfm(dta, forecast = 2)
#> Error in attr(x, "tsp") <- value: invalid time series parameters specified

fdeaths0[c(1:10, length(fdeaths0))] <- NA

dta.mixed <- ts_c(ts_pc(austres), mdeaths)

# why do these values don't ad up
fct <- predict(dfm(dta.mixed))
ts_plot(ts_c(dta.mixed, fct))
```

![](https://i.imgur.com/oVSSfd6.png)

<sup>Created on 2018-10-22 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by srlanalytics** [comment]
OK, all these little issues should be fixed. 

For the first, forecasting a single series: the C++ code requires that variable types are declared. Y should be a matrix, but for a single series the default in R is to convert Y to a vector. We now keep Y as a matrix using
`Y[,-(1:m), drop = FALSE]`

For the second, the ts stuff should now be OK (`class(Y)[1]` was `mts` which was not in `tsobjs`. I changed this to `any(class(Y)%in%tsobjs)` and added `mts` to `tsobjs`.)

For the third, the default is `dfm(Y, intercept = TRUE)`, but the bit of code that adds intercept terms back in to predicted values got lost in the formatting somewhere. Anyhow, it's back now. 

ps --- I'd not used `ts_plot()` before... very slick. Much nicer that `ts.plot()`!
