### ISSUE TITLE
Role of Seasonality

### ISSUE THREAD

**Issue by christophsax** [srlanalytics/BDFM#18]
I have a couple of questions about seasonality:

- Can I use non adjusted series in a dfm? E.g., #16 is a model with seasonal series. Is it ok to estimate it that way? Or should I seas adj. the series first?

- What is the use of `SeasAdj_WE` within `dfm`? This is just a tool to perform seasonal adjustment? So I could use it as an alternative to X-13 but I don't have to?

**Comment by srlanalytics** [comment]
One can estimate a DFM without seasonally adjusting data first, however, that's not recommended. It is almost always better to seasonally adjust data before estimating a factor model. With a model estimated by maximum likelihood, one can include seasonality as exogenous factors, but I've had better results (i.e. better nowcasts and forecasts) just cleaning out seasonality first. With MCMC estimation, including exogenous seasonal factors often leads to problems of weak identification --- simulations do not draw from the same distribution at each iteration and the model never converges. 

`SeasAdj_WE` is, as you say, just a tool to perform seasonal adjustment. It is an alternative to X-13 similar to Koopman et al. (2009)'s [STAMP software](https://www.jstatsoft.org/article/view/v041i02/v41i02.pdf) in that it models seasonality using a factor model framework. For non-technical users your [seasonal](http://www.seasonal.website/) package is almost always a better choice. Results for `SeasAdj_WE()` and `seas()` will be similar, though `SeasAdj_WE()` requires data is stationary. Aside from theoretical differences, the only real advantage of `SeasAdj_WE()` is that it can be applied to data at any frequency.

**Comment by srlanalytics** [comment]
@christophsax 

Another thought on this --- is it `SeasAdj_WE` is pretty raw compared to the rest of the package --- do you think it is better to maybe leave it out or have a development version, or something to that effect?

**Comment by christophsax** [comment]
> ... the only real advantage of SeasAdj_WE() is that it can be applied to data at any frequency.

which is of course a huge thing. 

It also has a clear connection to the dfm models. If we want to use, e.g., daily or weekly data in a bdfm, you would recommended to seasonally adjust it first, for which you need it, right?

I would suggest (of course to rename ;-)) but to keep it in the package and to flag it as experimental and mention that it may change in the future.

The code in `SeasAdj_WE` cries for out-factoring. If we keep it in the package, I will try.

**Comment by srlanalytics** [comment]
Yes, that's true if one wanted to use a dfm for higher frequency data. I'll try to clean it up a bit, but I think flagging it as experimental is a good idea.

**Comment by christophsax** [comment]
I can also clean it up. I had some ideas how to do it.

**Comment by christophsax** [comment]
Working now on `Preditermined.m`. Question:
```r
Predetermined.m(dates, predetermined = c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December", "Easter", "trading_days"))
```

Is there a use case for specifying months explicitly? Wouldn't it be sufficient to have one or several of the following options:

```r
predetermined = c("months", "quarters", "easter", "cny", "diwali", "trading_days")
```

**Comment by christophsax** [comment]
Question 2:

Is there a use of `predetermined.m` outside of `SeasAdj_WE`? Otherwise I would suggest to have a call to the seasonal adjustment function like this:

```
seas_we(data = AirPassengers, effect = c("months", "easter", "trading_days"))
```

`data` can be multivariate, right?

**Comment by christophsax** [comment]
No need to work on these function, I think I can simplify `Predetermined.m` substantially.

**Comment by srlanalytics** [comment]
`predetermined.m` and `predetermined.d` are only used by `seas_we`, so if we just want to call them from that function that would probably be cleaner. Happy to deffer to you on that.

**Comment by christophsax** [comment]
Thanks. Next question: Why are the seasonal effects weaker at the beginning and the end of lower frequency periods? Why not step-wise?

Here's an example for quarters (spring) in daily data:
﻿
[PastedGraphic-1.pdf](https://github.com/srlanalytics/BDFM/files/2670418/PastedGraphic-1.pdf)


﻿

**Comment by christophsax** [comment]
Perhaps the shape function could be provided by the user. Will give it a try.

**Comment by srlanalytics** [comment]
With daily effects I've rather arbitrarily gone with using a normal pdf as the shape function. There's no particular reason to do that... steps and hard 0/1 binaries just felt sort of unnatural. But user defined shape functions would certainly be a slick way to go that would open up a lot of possibilities.

**Comment by christophsax** [comment]
closing this. related questions are in separate issues #25 #24
