### ISSUE TITLE
seasonality: Role of intercept

### ISSUE THREAD

**Issue by christophsax** [srlanalytics/bdfm#25]
When building monthly dummies, we are currently building a dummy for each month, which makes it impossible to include an intercept, because we end up with singularity.

Perhaps we always should have an intercept and drop the January dummy? Same is true for weekdays and quarters.

Not sure if the following is related to the intercept: When I do an adjustment, the level is around 0, rather than around the original value:

``` r
library(BDFM)
m <- seas_we(mdeaths)
#> Loading required namespace: tsbox
adj_we <- predict(m)
library(seasonal)
#> 
#> Attaching package: 'seasonal'
#> The following object is masked from 'package:BDFM':
#> 
#>     cny
adj_x13 <- predict(seas(mdeaths))
tsbox::ts_plot(mdeaths, adj_x13, adj_we)
```

![](https://i.imgur.com/D1S2BLf.png)

<sup>Created on 2018-12-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by srlanalytics** [comment]
Doing an initial de-trending with `loess()` as I mentioned in dealing with stationarity would deal with this as well. Alternatively, we could de-mean the data before estimating effects then add the mean back in. I would rather do that than leave out January... that would effectively use January as our baseline which there is no real reason to do.

**Comment by srlanalytics** [comment]
De-trending and de-meaning are both in there now, so closing this... let me know if something else comes up!
