### ISSUE TITLE
Role of nu_r

### ISSUE THREAD

**Issue by christophsax** [srlanalytics/bdfm#34]
What is the role of `nu_r`? Don't get it from the documentation.

**Comment by srlanalytics** [comment]
Hopefully nu_r got changed to obs_df (i.e. prior "degrees of freedom" for each series in the observation equation). It allows the user to fit the model to particular series of interest by (from a maximum likelihood point of view, which is an easier way to think about it) penalizing errors in some series more than others. Thus if we're interested in a nowcast of GDP, it makes sense to enter 1 for GDP and zero elsewhere to fit our model to GDP. Of course this only guarantees an improved in-sample fit, not a better out of sample fit. But, if your in-sample fit is bad for sure out of sample forecasts will be bad too.

**Comment by christophsax** [comment]
This is ok now, added a line to the documentation
