### ISSUE TITLE
Function names

### ISSUE THREAD

**Issue by christophsax** [srlanalytics/BDFM#4]
> (1) I've changed variable names --- in the DFM literature there is a fairly established syntax and I've tried to make code in this package follow that syntax as much as possible (Y is observables, X is factors, Z is stacked (companion form) factors, and so on). Of course R code also has an established syntax which is not the same, so maybe that's not the best choice... If we want to go with more established R syntax that's fine

We could keep the underlying functions with their original names, `BDFM` and
`mlDFM`. These functions use the argument names from the Literature, and may even be exported, so that people familiar with the literature can use them.

For other users, we could have a single user interface function, `dfm` with an additional argument, `method = "baysian"` (the default) or `"ml"`. Since their input and output is the same, that would make a lot of sense, all the `predict`, `summary` would work for both methods.

**Comment by srlanalytics** [comment]
OK... good idea. I'll try to put something together on a branch for you to review.

**Comment by christophsax** [comment]
On using options to pass arguments.

I don't think it should be used. This will make calls hard to replicate. Same call may lead to different results and it is always hard to tell why. If people send you their code, you will often have to get back to them and ask them about their options.

I don't think it is a problem to have many arguments, where some arguments are unused by some methods. Popular functions such as `forecast::auto.arima` also have many arguments. The important thing is that it shows the user that is enough to deliver only the first argument. It does so in the example.

Also, the Bayesian method uses almost all arguments, and the ML method will be rarely used, as it is generally inferior, so really don't care that much about it.

So I would list all the arguments, but perhaps with longer more user friendly names.

**Comment by christophsax** [comment]
We may also export and document the core functions, `BDFM` etc, so that experienced users can use them for their experiments. Have a look at `?lm.fit` in R base: This is the workhorse of the `lm` function, and they tell you that you shouldn't use unless you are an experienced user. I like that.

**Comment by srlanalytics** [comment]
OK... lots of inputs is fine with me, and I like the idea of exporting core functions for advanced users.
