### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by christophsax** [srlanalytics/bdfm#44]
In RStudio, you can press Ctrl-Shift-T to run the integrated tests. Right now, the following mini example fails, but we would have spotted it with the test

``` r
  library(bdfm)
  fdeaths0 <- fdeaths
  fdeaths0[length(fdeaths0)] <- NA
  dta <- cbind(fdeaths0, mdeaths)

  m <- dfm(dta)
#> Error in PrinComp(Y[, long], m): Not a matrix.
```

<sup>Created on 2019-02-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

You can also adjust tests and add new ones in `tests/testthat`.

**Comment by srlanalytics** [comment]
This issue has been resolved and I've reinstated a few other tests too. I'll keep adding tests as we go, but things are running better now!
