### ISSUE TITLE
Nowcasting and "news" content of variables

### ISSUE THREAD

**Issue by srlanalytics** [srlanalytics/bdfm#47]
The gain_and_fit branch has been modified so that:

- if `store_idx` is specified, the forecast update contribution of each variable to the series specified by `store_idx`. The example us_gdp.R now includes an example of the contribution of each series to nowcast updates for a specified period. Updates to a specific series are stored as `idx_update`. If `scale = T` is specified (the default), forecast updates are unscaled before being returned. However, they remain in logs and/or differenced, so that these updates can be interpreted as percent change to the original variable. 

- in every case, forecast updates to factors are stored in `factor_update`

- gain and prediction error are no longer returned as updates are a far more concise and useful way to save this information. Advanced users can still access gain and prediction error through `Cppbdfm()`.

@christophsax --- `idx_update` and `forecast_update` are lists. Right now individual elements can only be accessed by index (i.e. `est$idx_update[[460]]`). If input data are `ts_boxable()` it would be nice to be able to call these results by date (i.e. what was the contribution of each series to the nowcast on 2018-03-31?). Any ideas on the best way to do this?

**Comment by christophsax** [comment]
`m$idx_update` is now a multiple time series and can be accessed, e.g., by:

```r
window(m$idx_update, start = c(2018, 12), end = c(2018, 12))
```

Adjusted example in `us_gdp.R`.

**Comment by christophsax** [comment]
We should include a section on this in the vignette, this seems important.
