### ISSUE TITLE
Errors for method = "ml"

### ISSUE THREAD

**Issue by christophsax** [srlanalytics/bdfm#48]
``` r
library(bdfm)
m1 <- dfm(cbind(fdeaths, mdeaths), method = "ml") #multivariate example
#> Error in dfm(cbind(fdeaths, mdeaths), method = "ml"): Mixed freqeuncy models are only supported for Bayesian estimation
m3 <- dfm(fdeaths, method = "ml") #univariate example
#> Error in dfm(fdeaths, method = "ml"): Mixed freqeuncy models are only supported for Bayesian estimation
```

<sup>Created on 2019-03-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by christophsax** [comment]
duplicate of #38

**Comment by christophsax** [comment]
Probably not the same, but `method = "ml"` is not working:

``` r
library(bdfm)
dfm(mdeaths, method = 'ml')
#> Error in DSmooth(B, Jb = Jb, q, H, R, Y = Ydm, freq = rep(1, k), LD = rep(0, : Not a matrix.
```

<sup>Created on 2019-06-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by christophsax** [comment]
Fixing this and including the test would probably bring test coverage to a satisfying level.

**Comment by SethOttoQuant** [comment]
OK... should be fine now. B was being entered as a sparse matrix in DSmooth(), needs to be a dense matrix.
