### ISSUE TITLE
Exploding Forecast of T10Y3M

### ISSUE THREAD

**Issue by christophsax** [srlanalytics/bdfm#56]
``` r
library(bdfm)
m <- dfm(data = econ_us, factors = 3, pre_differenced = "A191RL1Q225SBEA", store_idx = "A191RL1Q225SBEA")
```

``` r
tsbox::ts_plot(predict(m)[, 'T10Y3M'])
```

![](https://i.imgur.com/aI35m2G.png)

<sup>Created on 2019-03-24 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by christophsax** [comment]
I guess this comes back to the usual problem of using non-stationary series in the BDFM. It seems that your diff algo is not keen enough about differentiating. 

### Original Manual Log Diff Choice

From your original example: 

``` r
logs0 <- c(
  "W068RCQ027SBEA",
  "PCEDG",
  "PCEND",
  "JTSJOL",
  "INDPRO",
  "CSUSHPINSA",
  "HSN1F",
  "TSIFRGHT",
  "IPG2211S",
  "DGORDER",
  "AMTMNO",
  "CPILFESL",
  "ICSA"
)

diffs0 <- c(
  "W068RCQ027SBEA",
  "PCEDG",
  "PCEND",
  "UMCSENT",
  "UNRATE",
  "JTSJOL",
  "INDPRO",
  "CSUSHPINSA",
  "HSN1F",
  "TSIFRGHT",
  "FRGSHPUSM649NCIS",
  "CAPUTLG2211S",
  "IPG2211S",
  "DGORDER",
  "AMTMNO",
  "MNFCTRIRSA",
  "RETAILIRSA",
  "WHLSLRIRSA",
  "CPILFESL",
  "ICSA",
  "TWEXB",
  "T10Y3M"
)

library(bdfm)
m <- dfm(data = econ_us, logs = logs0, diffs = diffs0, factors = 3, pre_differenced = "A191RL1Q225SBEA", store_idx = "A191RL1Q225SBEA")
```

Which leads to a nice forecast:

``` r
tsbox::ts_plot(predict(m)[, 'T10Y3M'])
```

![](https://i.imgur.com/HJgo89F.png)

### Automatic Log Diff Choice

However, with the automatic, choice the forecasts goes nuts:

``` r
m <- dfm(data = econ_us, factors = 3, pre_differenced = "A191RL1Q225SBEA", store_idx = "A191RL1Q225SBEA")
```

``` r
tsbox::ts_plot(predict(m)[, 'T10Y3M'])
```

![](https://i.imgur.com/DUi4QgE.png)

Same if we add logs and diffs manually (so technically, this works as advertised):

``` r
logs = c(
  "W068RCQ027SBEA",
  "PCEND",
  "CSUSHPINSA"
)
diffs = c(
  "W068RCQ027SBEA",
  "PCEDG",
  "PCEND",
  "UNRATE",
  "JTSJOL",
  "INDPRO",
  "CSUSHPINSA",
  "TSIFRGHT",
  "IPG2211S",
  "AMTMNO",
  "RETAILIRSA",
  "TWEXB"
)

m <- dfm(data = econ_us, logs = logs, diffs = diffs, factors = 3, pre_differenced = "A191RL1Q225SBEA", store_idx = "A191RL1Q225SBEA")
```

``` r
tsbox::ts_plot(predict(m)[, 'T10Y3M'])
```

![](https://i.imgur.com/00mDTYO.png)

Auto diff log has all the manual choices but manual has much more. It seems we simply don’t log and diff enough:

``` r
setdiff(logs, logs0)
#> character(0)
setdiff(logs0, logs)
#>  [1] "PCEDG"    "JTSJOL"   "INDPRO"   "HSN1F"    "TSIFRGHT" "IPG2211S"
#>  [7] "DGORDER"  "AMTMNO"   "CPILFESL" "ICSA"

setdiff(diffs, diffs0)
#> character(0)
setdiff(diffs0, diffs)
#>  [1] "UMCSENT"          "HSN1F"            "FRGSHPUSM649NCIS"
#>  [4] "CAPUTLG2211S"     "DGORDER"          "MNFCTRIRSA"      
#>  [7] "WHLSLRIRSA"       "CPILFESL"         "ICSA"            
#> [10] "T10Y3M"
```

<sup>Created on 2019-03-24 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by srlanalytics** [comment]
I turned the rule for automatic differencing up to require the estimated AR(1) coefficient must be three standard deviations less than one (one being a random walk and therefore not stationary). That seems very aggressive but is actually still less strict than the difference we specified manually, so it's probably fine. It should certainly err on the side of stationary results.

**Comment by christophsax** [comment]
This is resolved

``` r
library(bdfm)
m <- dfm(data = econ_us, factors = 3, pre_differenced = "A191RL1Q225SBEA", keep_posterior = "A191RL1Q225SBEA")
```

``` r

tsbox::ts_plot(predict(m)[, 'T10Y3M'])
```

![](https://i.imgur.com/ACqfDRB.png)

<sup>Created on 2019-06-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
