### ISSUE TITLE
Revise Vignette

### ISSUE THREAD

**Issue by christophsax** [srlanalytics/bdfm#68]
The following sections need revision:

## Full Posterior Distributions of Predicted Values

- better explain why we need full posterior distribution
- clearly show how it can be used to do a forecast (proving that is better is not so important, i.m.O.)

## Forecast Updates

- also discussed in #47 

## Other Estimation Methods

- But these should be fixed first.

**Comment by christophsax** [comment]
The part on 'Other Estimation Methods' is now good.

Still open are the sections on:

- [ ] Full Posterior Distributions of Predicted Values
- [ ] Forecast Updates

**Comment by SethOttoQuant** [comment]
OK... made some revisions and included a lot of additional notes. Let me know if that all makes sense.

**Comment by christophsax** [comment]
Thanks, seems clearer now. I will try now to go over the sections on 'Full Posterior Distributions of Predicted Values' and 'Forecast Updates' myself. Assigning to me.

**Comment by christophsax** [comment]
For the forecast updates, also consider #47

**Comment by christophsax** [comment]
Still an open discussion on whether to store median for all series:

https://github.com/srlanalytics/bdfm/issues/83

Otherwise, vignette is fine.
