### ISSUE TITLE
Test Coverage Report

### ISSUE THREAD

**Issue by christophsax** [srlanalytics/BDFM#7]
Also, you should sign in here and connect this repo. This should produce a test coverage report.

https://codecov.io

<img width="108" alt="image" src="https://user-images.githubusercontent.com/1390827/47230338-476d4c80-d3ca-11e8-8535-5de338188330.png">

This will give us a little batch that shows how much of the code is automatically tested.

**Comment by srlanalytics** [comment]
OK, linked the account but I've not done anything else.
