### ISSUE TITLE
E-Mail down

### ISSUE THREAD

**Issue by christophsax** [srlanalytics/bdfm#70]
Hi @srlanalytics 

Wanted to write you an email, but address seems down.

Finally found time to work on bdfm. See my PR for details: https://github.com/srlanalytics/bdfm/pull/66

I think it is relatively clear what we still need to do. I started a 'project' on GitHub, which should give us a good overview of what needs to be done:

https://github.com/srlanalytics/bdfm/projects/1

All the open issues are now assigned to you. If you need input from my side, just assign them back.

We are getting closer!

**Comment by SethOttoQuant** [comment]
Hi @christophsax,

Thanks for that! Yes... that e-mail is out of commission at the moment as I am trying to switch the account from Wix (where I had a job market website before I knew how to do anything myself...) to Google. Wix says it's Google's problem and Google says it's Wix's problem...

I'll take a look at the project and see what I can get done.
